name: "pr"
on:
  pull_request:
    # To avoid running this on WIP PRs, consider: types: [review_requested, ready_for_review]
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: wearehanno/action-semantic-pull-request@v3.2.6 # Change this to @main if you want to lock it to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
